name: ci-check

on: [push, pull_request]

jobs:
  ci-check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Run CI Checks
        run: yarn lint && yarn lint:styles
